# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - dmitry_c2000@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

    # после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
    # Здесь используется сторонний сервис https://codecov.io/
    after_success:
      - bash <(curl -s https://codecov.io/bash)

        env:
      global:
        #- CODECOV_TOKEN='7ad919b5-4adc-4608-912e-5c8cc6875724'
        - CODECOV_TOKEN="6da04485-7d5f-433d-bff1-74b34cc1d1aa"

